quarkus.http.port=8078
quarkus.http.cors.origins=http://localhost:4200,http://localhost:8080,https://samoa.se.informatik.uni-kiel.de,https://explorviz.sustainkieker.kieker-monitoring.net
quarkus.http.cors=true
quarkus.http.cors.methods=GET,PUT,POST,DELETE
quarkus.http.cors.access-control-max-age=24H
quarkus.http.cors.access-control-allow-credentials=true
quarkus.banner.path=explorviz-banner.txt
quarkus.devservices.enabled=false
##########
## gRPC ##
##########
quarkus.grpc.dev-mode.force-server-start=false
quarkus.grpc.clients.codeAnalysisGrpcClient.host=${PERSISTENCE_HOSTNAME:127.0.0.1}
%test.quarkus.grpc.clients.codeAnalysisGrpcClient.host=localhost
quarkus.grpc.clients.codeAnalysisGrpcClient.port=${GRPC_PORT:9000}
%test.quarkus.grpc.clients.codeAnalysisGrpcClient.port=9123
############################
## ExplorViz Git Analysis ##
############################
explorviz.gitanalysis.run-mode=${ANALYSIS_RUN_MODE:api}
explorviz.gitanalysis.local.storage-path=${ANALYSIS_LOCAL_PATH:${CI_PROJECT_DIR:}}
%test.explorviz.gitanalysis.local.storage-path=
explorviz.gitanalysis.remote.url=${ANALYSIS_REMOTE_URL:${CI_REPOSITORY_URL:}}
%test.explorviz.gitanalysis.remote.url=
explorviz.gitanalysis.remote.storage-path=${ANALYSIS_STORAGE_PATH:cloned-repositories}
explorviz.gitanalysis.branch=${ANALYSIS_BRANCH:${CI_COMMIT_BRANCH:}}
explorviz.gitanalysis.remote.username=${ANALYSIS_USERNAME:}
explorviz.gitanalysis.remote.password=${ANALYSIS_PASSWORD:}
explorviz.gitanalysis.fetch-remote-data=${ANALYSIS_FETCH_REMOTE:false}
%test.explorviz.gitanalysis.fetch-remote-data=false
explorviz.gitanalysis.send-to-remote=${ANALYSIS_SEND_TO_REMOTE:false}
%test.explorviz.gitanalysis.local.send-to-remote=false
explorviz.gitanalysis.include-in-analysis-expressions=${ANALYSIS_INCLUSION_EXPRESSIONS:}
explorviz.gitanalysis.exclude-from-analysis-expressions=${ANALYSIS_EXCLUSIONS_EXPRESSIONS:}
explorviz.gitanalysis.start-commit-sha1=${ANALYSIS_START_COMMIT:${CI_COMMIT_BEFORE_SHA:}}
explorviz.gitanalysis.end-commit-sha1=${ANALYSIS_END_COMMIT:${CI_COMMIT_SHA:}}
explorviz.gitanalysis.commit-analysis-limit=${COMMIT_ANALYSIS_LIMIT:}
explorviz.gitanalysis.calculate-metrics=${ANALYSIS_CALCULATE_METRICS:true}
explorviz.gitanalysis.assume-unresolved-types-from-wildcard-imports=${ANALYSIS_RESOLVE_WILDCARDS:false}
explorviz.gitanalysis.save-crashed_files=${ANALYSIS_SAVE_CRASHED_FILES:false}
explorviz.landscape.token=${EXPLORVIZ_LANDSCAPE_TOKEN:mytokenvalue}
explorviz.landscape.secret=${EXPLORVIZ_LANDSCAPE_SECRET:mytokensecret}
explorviz.gitanalysis.application-name=${ANALYSIS_APPLICATION_NAME:default-application-name}
#############################
## ExplorViz Logging Level ##
#############################
quarkus.log.level=INFO
quarkus.log.min-level=TRACE
quarkus.log.category."net.explorviz".level=${EXPLORVIZ_LOG_LVL:INFO}
%dev.quarkus.log.category."net.explorviz".level=${EXPLORVIZ_LOG_LVL:TRACE}
%test.quarkus.log.category."net.explorviz".level=${EXPLORVIZ_LOG_LVL:TRACE}
#####################
## Jib Image Build ##
#####################
quarkus.container-image.group=explorviz
quarkus.container-image.name=code-agent-jvm
quarkus.container-image.tag=latest
quarkus.jib.base-jvm-image=eclipse-temurin:21.0.1_12-jdk-alpine@sha256:075f8207cbfecf7e509e2d93e2ffc36c097b52a8109a9bfd40326fa12bd5c438
